manga-downloader.env: ENC[AES256_GCM,data:aG/O6D+EN+aBK4TlaW7qlzGkUQ4uEnLrj87KCQDSsNEzl2lR4Bru1jGfYPZQKPvUJIbnLXUpa4K8IZj8t6L2yVlVzPWoKlyyC0/CpDgSZkET,iv:aMdCZxzFSLpasJ1dchlH370HTZ3/pJpP3RIfKH6bj6Q=,tag:QGJKFr3/AaQKtNugoCge6Q==,type:str]
grafana.env: ENC[AES256_GCM,data:QTOJJulvcs1HrpPQNw1leRrnrmb2DBkyuuUs9cWEKrcnUvpBZ4YTD3oGyosnveojGDM8DkW1ds08lR1+YhA1cTIi+7pzezzeBPGt3jHVRwVUR4u+GdRyl8B8hoC6xydsuAkXsRJbV8IVAwx00chDCXgXn/vn9Y40/QTAGUd+ALnrEYL80HM2OdFkFoMC6IDgKcRhHvuOpAaYUnqURln7NhJvUpgLLHvkMEp8Hb3wNpdQmKu41IDEzssoC8VGQkw5aaz/3bfFBFVstPXiOk0q8G86xcySyFNIh6KpICGvGaNUWK1rSBwHd+rXHA8AR1mPUoTPG7PIIfaMj5xzgzjw8mlK45f0b5s3hgoBRM35+cSakPTeQOrgmq4=,iv:MUdPNA83ripfebjPcrIQR94rLPkqyLqUHP+SNVwjr3o=,tag:kc/kaMnRL0rGH+cGo5leTA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaGpkUmhZT2pjM05QWlZ3
            NkpJMFZ1YW5uSnNwdVV5NUhnVUI0Rk9XUmdFCjh1a2xzbzZZYjFsRjBQcGV5Q2ND
            Yi9TYUhBcTFwYkttbzZhdkVUdEhEUm8KLS0tIFRZU0dCVHZPWlB1eCs3SjVuMUpX
            UGdxOHBJbzhCZk9VSG5aZHpYK2U0Y0EKhaW9SkikDPSadXJ0JaR+zCz075lSpfYZ
            izXzSaoHdLSJMgPJAHcfwdBHVZhQGYeaXxOjFeoXYuP2ZN/auMnOww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywsx3kwnyp9ntuf2plpr6y6wajc6ypefxz87jsf7clry75g2dc7s5hlvtu
    lastmodified: "2026-06-11T08:29:23Z"
    mac: ENC[AES256_GCM,data:/SV6dczrYj+5JSmQ0Ej3Zi2HlsaLiz/5H98QMJr79P+wAYZg+24eqNjNAbejGFhgYnG6dxIa7p8h1r8VACMQC1Pxfcl29i+VDBQ0eho2rbY4ceVhCcgQ/72nL4GI82p/zrfI3Bwf+kXSkIAMVSEnmiee6UPVJ9S/Z+jaG3Amfbc=,iv:4VAsWXXERrQ+moaEmeak8htZ6yRfGhNlR3bdxZPOAmw=,tag:mEDk8KRtyRJYu2Z4zWwONQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
