load("@aspect_rules_js//js:defs.bzl", "js_test")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "starlark_files",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)

test_suite(
    name = "rustfmt_test",
    tests = [
        "//apps:rustfmt_test",
        "//libs:rustfmt_test",
        "//stress-testing:rustfmt_test",
    ],
)

filegroup(
    name = "clippy_check",
    testonly = True,
    srcs = [
        "//apps:clippy_check",
        "//libs:clippy_check",
        "//stress-testing:clippy_check",
    ],
)

js_test(
    name = "root_lint",
    args = [
        "oxlint",
        "oxlint",
        "vite.config.ts",
    ],
    data = [
        "//:node_modules",
        "//:root_oxc_files",
    ],
    entry_point = "//:run_npm_bin",
)

js_test(
    name = "root_format_oxc_js_ts_check",
    args = [
        "oxfmt",
        "oxfmt",
        "--check",
        "vite.config.ts",
    ],
    data = [
        "//:node_modules",
        "//:root_oxc_files",
    ],
    entry_point = "//:run_npm_bin",
)

js_test(
    name = "root_format_oxc_json_check",
    args = [
        "oxfmt",
        "oxfmt",
        "--check",
        "package.json",
        "renovate.json",
    ],
    data = [
        "//:node_modules",
        "//:root_oxc_files",
    ],
    entry_point = "//:run_npm_bin",
)

test_suite(
    name = "lint",
    tests = [
        ":root_lint",
        "//apps/svelte:lint",
        "//libs/svelte:lint",
        "//observability:lint",
        "//stress-testing:lint",
    ],
)

test_suite(
    name = "format_oxc_js_ts_check",
    tests = [
        ":root_format_oxc_js_ts_check",
        "//apps/svelte:format_oxc_js_ts_check",
        "//libs/svelte:format_oxc_js_ts_check",
        "//observability:format_oxc_js_ts_check",
        "//stress-testing:format_oxc_js_ts_check",
    ],
)

test_suite(
    name = "format_oxc_json_check",
    tests = [
        ":root_format_oxc_json_check",
        "//apps/svelte:format_oxc_json_check",
        "//libs/svelte:format_oxc_json_check",
        "//observability:format_oxc_json_check",
    ],
)

test_suite(
    name = "format_oxc_check",
    tests = [
        ":format_oxc_js_ts_check",
        ":format_oxc_json_check",
    ],
)
