load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")
load("//libs/bazel/rust:defs.bzl", "rust_quality_targets")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "core",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "backend_core",
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//libs/rust/fs",
        "@backend_crates//:anyhow",
        "@backend_crates//:byte-unit",
        "@backend_crates//:jiff",
        "@backend_crates//:quick-xml",
        "@backend_crates//:sanitize-filename",
    ],
)

rust_test(
    name = "test_comicinfo",
    srcs = ["tests/comicinfo.rs"],
    crate_root = "tests/comicinfo.rs",
    edition = "2024",
    deps = [
        ":core",
        "//libs/rust/fs",
        "@backend_crates//:anyhow",
        "@backend_crates//:byte-unit",
        "@backend_crates//:jiff",
        "@backend_crates//:quick-xml",
        "@backend_crates//:sanitize-filename",
    ],
)

rust_quality_targets(
    targets = [
        ":core",
        ":test_comicinfo",
    ],
)

filegroup(
    name = "rust_files",
    srcs = glob(
        [
            "src/**/*.rs",
            "tests/**/*.rs",
        ],
        allow_empty = True,
    ),
    tags = ["rust"],
)

filegroup(
    name = "starlark_files",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)
