load("@rules_rust//rust:defs.bzl", "rust_binary")
load("//libs/bazel/rust:defs.bzl", "rust_quality_targets")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "starlark_files",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)

filegroup(
    name = "rust_files",
    srcs = ["runner.rs"],
    tags = ["rust"],
)

rust_binary(
    name = "server",
    srcs = ["runner.rs"],
    args = [
        "$(rootpath @cargo_tools_crates//:flamegraph__flamegraph)",
        "$(rootpath //apps/rust/server:server)",
        "server",
    ],
    crate_name = "manga_flamegraph_server",
    crate_root = "runner.rs",
    data = [
        "//apps/rust/server",
        "@cargo_tools_crates//:flamegraph__flamegraph",
    ],
    edition = "2024",
    tags = [
        "flamegraph",
        "manual",
        "requires-local-profiler",
    ],
)

rust_quality_targets(
    targets = [":server"],
)
