load("@aspect_rules_js//js:defs.bzl", "js_library", "js_test")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("@npm//libs/svelte/ui:svelte-check/package_json.bzl", svelte_check = "bin")

package(default_visibility = ["//visibility:public"])

npm_link_all_packages()

filegroup(
    name = "starlark_files",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)

filegroup(
    name = "sources",
    srcs = glob([
        "src/**/*.svelte",
        "src/**/*.ts",
        "*.json",
    ]),
)

js_library(
    name = "pkg",
    srcs = [":sources"],
    deps = [
        ":node_modules/@lucide/svelte",
        ":node_modules/clsx",
        ":node_modules/tailwind-merge",
    ],
)

js_test(
    name = "lint",
    args = [
        "oxlint",
        "oxlint",
        "libs/svelte/ui",
    ],
    data = [
        ":pkg",
        "//:node_modules",
        "//:root_oxc_files",
    ],
    entry_point = "//:run_npm_bin",
)

js_test(
    name = "format_oxc_js_ts_check",
    args = [
        "oxfmt",
        "oxfmt",
        "--check",
        "libs/svelte/ui",
    ],
    data = [
        ":pkg",
        "//:node_modules",
        "//:root_oxc_files",
    ],
    entry_point = "//:run_npm_bin",
)

js_test(
    name = "format_oxc_json_check",
    args = [
        "oxfmt",
        "oxfmt",
        "--check",
        "libs/svelte/ui/package.json",
        "libs/svelte/ui/tsconfig.json",
    ],
    data = [
        ":pkg",
        "//:node_modules",
        "//:root_oxc_files",
    ],
    entry_point = "//:run_npm_bin",
)

svelte_check.svelte_check_test(
    name = "typecheck",
    args = [
        "--tsconfig",
        "tsconfig.json",
    ],
    chdir = package_name(),
    data = [
        ":node_modules",
        ":sources",
    ],
)
