load("@rules_rust//rust:defs.bzl", "rust_library")
load("//libs/bazel/rust:defs.bzl", "rust_quality_targets")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "cache",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "backend_cache",
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "//libs/rust/core",
        "//libs/rust/fs",
        "//libs/rust/runtime",
        "@backend_crates//:anyhow",
        "@backend_crates//:bytes",
        "@backend_crates//:foyer",
        "@backend_crates//:metrics",
        "@backend_crates//:mixtrics",
        "@backend_crates//:rkyv",
        "@backend_crates//:serde",
        "@backend_crates//:serde_json",
        "@backend_crates//:tracing",
    ],
)

rust_quality_targets(
    targets = [":cache"],
)

filegroup(
    name = "rust_files",
    srcs = glob(
        [
            "src/**/*.rs",
            "tests/**/*.rs",
        ],
        allow_empty = True,
    ),
    tags = ["rust"],
)

filegroup(
    name = "starlark_files",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)
