[package]
name = "backend-discord"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "backend_discord"
path = "src/lib.rs"

[dependencies]
backend-core = { path = "../core" }
backend-persistence = { path = "../persistence" }
backend-plugin-host = { path = "../plugin-host" }
anyhow.workspace = true
autometrics.workspace = true
jiff.workspace = true
secrecy.workspace = true
tokio.workspace = true
tokio-graceful.workspace = true
tracing.workspace = true
twilight-gateway.workspace = true
twilight-http.workspace = true
twilight-interactions.workspace = true
twilight-model.workspace = true
url.workspace = true
