[package]
name = "backend-plugin-host"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "backend_plugin_host"
path = "src/lib.rs"

[dependencies]
backend-clearance = { path = "../clearance" }
backend-core = { path = "../core" }
backend-fs = { path = "../fs" }
backend-image = { path = "../image" }
backend-tls = { path = "../tls" }
anyhow.workspace = true
base64.workspace = true
bytecheck.workspace = true
reqwest.workspace = true
rkyv.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower.workspace = true
tower-resilience-coalesce.workspace = true
tower-resilience-retry.workspace = true
tracing.workspace = true
url.workspace = true
utoipa.workspace = true
wasmtime.workspace = true
wasmtime-wasi.workspace = true
