load("@rules_rust//rust:defs.bzl", "rust_library")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "manga-plugin-kit",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "manga_plugin_kit",
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "@backend_crates//:serde",
        "@backend_crates//:serde_json",
    ],
)

filegroup(
    name = "rust_files",
    srcs = glob(["src/**/*.rs"]),
    tags = ["rust"],
)

filegroup(
    name = "starlark_files",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)
