#![allow(clippy::missing_errors_doc)]

mod api_tokens;
pub use api_tokens::ApiTokenRow;
mod auth;
mod background_jobs;
mod chapters;
mod download_work_state;
mod downloads;
mod maintenance;
mod manga;
mod migrations;
mod models;
mod schema;
mod settings;
mod upscale_progress;
pub use upscale_progress::UpscaleProgressRow;
mod setup;
mod sources;
mod stats;

use anyhow::Result;
use std::{
    sync::Arc,
    time::{SystemTime, UNIX_EPOCH},
};
use toasty::Db;
use tokio::sync::{Mutex, MutexGuard};

use backend_core::settings::SETTING_DEFINITIONS;

pub use auth::{AuthSessionRecord, AuthUser, PublicShareRecord};
pub use backend_core::settings::setting_default;
pub use background_jobs::{BackgroundJobFailureOutcome, BackgroundJobLease, BackgroundJobStatus};
pub use download_work_state::{DownloadWorkStatus, DownloadWorkTransition};
pub use maintenance::DatabaseCleanupResult;
pub use models::{
    ChapterInsert, ChapterRow, DownloadMetricRow, DownloadRow, MangaInsert, MangaRow,
    SourceCountRow, SourceRecordInput, StatsActivityPoint, StatsCacheSummary, StatsOverview,
    StatsRecentChapter, StatsSourceBreakdown, StatsStorageSummary, StatsTotals,
};
pub use setup::{
    DatabaseMigration, SqliteDatabaseOptions, apply_sqlite_migrations, configure_sqlite_connection,
    database_parent_dir, ensure_database_parent_dir, open_configured_sqlite_connection,
    open_sqlite_database, setup_sqlite_database,
};

#[derive(Clone, Copy, Debug, PartialEq, Eq, serde::Serialize)]
#[serde(rename_all = "lowercase")]
pub enum DatabaseBackend {
    Sqlite,
    Postgres,
}
impl DatabaseBackend {
    pub fn from_url(url: &str) -> Self {
        if url.starts_with("postgres://") || url.starts_with("postgresql://") {
            Self::Postgres
        } else {
            Self::Sqlite
        }
    }
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Sqlite => "sqlite",
            Self::Postgres => "postgres",
        }
    }
}

pub fn redacted_database_url(value: &str) -> String {
    if DatabaseBackend::from_url(value) == DatabaseBackend::Sqlite {
        return value.to_string();
    }
    match url::Url::parse(value) {
        Ok(mut url) => {
            let _ = url.set_username("");
            let _ = url.set_password(None);
            url.set_query(None);
            url.to_string()
        }
        Err(_) => "[invalid PostgreSQL URL]".into(),
    }
}

pub fn sqlite_path(value: &str) -> &str {
    value.strip_prefix("sqlite://").unwrap_or(value)
}

/// Apply the bundled initial schema for the chosen backend.
pub async fn migrate_database(url: &str) -> Result<()> {
    match DatabaseBackend::from_url(url) {
        DatabaseBackend::Sqlite => {
            setup_sqlite_database(
                sqlite_path(url),
                migrations::SQLITE_MIGRATIONS,
                SqliteDatabaseOptions::default(),
            )
            .await
        }
        DatabaseBackend::Postgres => {
            setup::apply_postgres_migrations(url, migrations::POSTGRES_MIGRATIONS).await
        }
    }
}

/// Generate a fresh schema from the registered models, without connecting.
pub fn generate_schema(backend: DatabaseBackend) -> Result<String> {
    use toasty_core::driver::Driver;
    let driver: Box<dyn Driver> = match backend {
        DatabaseBackend::Sqlite => Box::new(toasty_driver_sqlite::Sqlite::in_memory()),
        DatabaseBackend::Postgres => Box::new(toasty_driver_postgresql::PostgreSQL::new(
            "postgresql://localhost/manga",
        )?),
    };
    let mut builder = Db::builder();
    builder.models(toasty::models!(crate::*));
    let schema = toasty_core::schema::Builder::new()
        .build(builder.build_app_schema()?, driver.capability())?;
    let empty = toasty_core::schema::db::Schema::default();
    let hints = toasty_core::schema::diff::RenameHints::new();
    let diff = toasty_core::schema::diff::Schema::from(&empty, &schema.db, &hints);
    let toasty_core::schema::db::Migration::Sql(sql) = driver.generate_migration(&diff);
    // The model registry's hash iteration order varies between processes.
    // There are no cross-table foreign keys in this schema; emit all tables
    // before their indexes, each in stable order, for reproducible generation.
    let sql = sql.replace("-- #[toasty::breakpoint]", "");
    let mut statements = sql
        .split_inclusive(';')
        .map(str::trim)
        .filter(|sql| !sql.is_empty())
        .collect::<Vec<_>>();
    statements.sort_by_key(|sql| (!sql.starts_with("CREATE TABLE"), *sql));
    let sql = statements.join("\n-- #[toasty::breakpoint]\n");
    Ok(format!(
        "-- Generated by cargo run -p backend-persistence --example generate-schema.\n{sql}\n-- #[toasty::breakpoint]\n{}",
        include_str!("../migrations/constraints.sql")
    ))
}

#[derive(Clone)]
pub struct Database {
    db: Db,
    path: Arc<str>,
    backend: DatabaseBackend,
    write_lock: Option<Arc<Mutex<()>>>,
}

impl Database {
    /// Open SQLite (the default) or PostgreSQL, migrate it, and seed settings.
    pub async fn open(url: &str) -> Result<Self> {
        let backend = DatabaseBackend::from_url(url);
        let path = if backend == DatabaseBackend::Sqlite {
            sqlite_path(url)
        } else {
            url
        };
        let db = match backend {
            DatabaseBackend::Sqlite => {
                open_sqlite_database(
                    path,
                    toasty::models!(crate::*),
                    migrations::SQLITE_MIGRATIONS,
                    SqliteDatabaseOptions::default(),
                )
                .await?
            }
            DatabaseBackend::Postgres => {
                setup::open_postgres_database(
                    path,
                    toasty::models!(crate::*),
                    migrations::POSTGRES_MIGRATIONS,
                )
                .await?
            }
        };
        let database = Self {
            db,
            path: Arc::from(path),
            backend,
            write_lock: (backend == DatabaseBackend::Sqlite).then(|| Arc::new(Mutex::new(()))),
        };
        database.seed_default_settings().await?;
        Ok(database)
    }
    pub fn backend(&self) -> DatabaseBackend {
        self.backend
    }
    pub fn connection_url(&self) -> &str {
        &self.path
    }
    pub async fn ping(&self) -> Result<()> {
        self.get_setting("download_path").await?;
        Ok(())
    }

    /// Applies non-empty environment variable overrides for known settings.
    pub async fn apply_env_overrides(&self) -> Result<()> {
        for definition in SETTING_DEFINITIONS {
            if let Ok(value) = std::env::var(definition.env_var) {
                if value.trim().is_empty() {
                    continue;
                }
                self.set_setting(definition.key, &value).await?;
            }
        }

        Ok(())
    }

    pub(crate) fn executor(&self) -> Db {
        self.db.clone()
    }

    pub(crate) async fn write_guard(&self) -> Option<MutexGuard<'_, ()>> {
        match &self.write_lock {
            Some(lock) => Some(lock.lock().await),
            None => None,
        }
    }

    pub(crate) fn path(&self) -> &str {
        &self.path
    }
}

pub(crate) fn new_id() -> String {
    uuid::Uuid::now_v7().to_string()
}

pub(crate) fn now_timestamp() -> String {
    format!(
        "{:020}",
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis()
    )
}

pub(crate) fn split_csv(input: &str) -> Vec<String> {
    input
        .split(',')
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(ToOwned::to_owned)
        .collect()
}

const DECIMAL_SCALE: f64 = 1_000_000.0;
const PROGRESS_SCALE: f64 = 1_000.0;

#[allow(clippy::cast_possible_truncation)]
pub(crate) fn encode_chapter_number(value: f64) -> i64 {
    (value * DECIMAL_SCALE).round() as i64
}

#[allow(clippy::cast_precision_loss)]
pub(crate) fn decode_chapter_number(value: i64) -> f64 {
    value as f64 / DECIMAL_SCALE
}

#[allow(clippy::cast_possible_truncation)]
pub(crate) fn encode_progress(value: f64) -> i64 {
    (value * PROGRESS_SCALE).round() as i64
}

#[allow(clippy::cast_precision_loss)]
pub(crate) fn decode_progress(value: i64) -> f64 {
    value as f64 / PROGRESS_SCALE
}
