-- Generated by cargo run -p backend-persistence --example generate-schema.
CREATE TABLE "app_settings" (
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    PRIMARY KEY ("key")
);
-- #[toasty::breakpoint]
CREATE TABLE "background_jobs" (
    "id" TEXT NOT NULL,
    "queue" TEXT NOT NULL,
    "payload_json" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "attempt_count" BIGINT NOT NULL,
    "max_attempts" BIGINT NOT NULL,
    "run_after" TEXT NOT NULL,
    "locked_by" TEXT,
    "locked_at" TEXT,
    "last_error" TEXT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE TABLE "chapters" (
    "id" TEXT NOT NULL,
    "series_id" TEXT NOT NULL,
    "remote_chapter_id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "number" BIGINT NOT NULL,
    "published_at" TEXT NOT NULL,
    "is_new" BOOLEAN NOT NULL,
    "pages_read" BIGINT NOT NULL,
    "read_completed" BOOLEAN NOT NULL,
    "last_read_at" TEXT,
    "fetched_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE TABLE "download_events" (
    "id" TEXT NOT NULL,
    "download_id" TEXT NOT NULL,
    "event_type" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "payload_json" TEXT,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE TABLE "downloads" (
    "id" TEXT NOT NULL,
    "series_id" TEXT NOT NULL,
    "chapter_id" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "progress_percent" BIGINT NOT NULL,
    "stage" TEXT NOT NULL,
    "error_code" TEXT,
    "error_message" TEXT,
    "upscaled_at" TEXT,
    "upscale_model" TEXT,
    "upscale_scale" BIGINT,
    "file_path" TEXT,
    "file_size_bytes" BIGINT,
    "page_count" BIGINT NOT NULL,
    "attempt_count" BIGINT NOT NULL,
    "queued_at" TEXT NOT NULL,
    "started_at" TEXT,
    "finished_at" TEXT,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE TABLE "library_series" (
    "id" TEXT NOT NULL,
    "source_key" TEXT NOT NULL,
    "remote_series_id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "cover_url" TEXT NOT NULL,
    "cover_fetch_spec" TEXT,
    "description" TEXT NOT NULL,
    "author" TEXT NOT NULL,
    "genres" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "is_nsfw" BOOLEAN NOT NULL,
    "auto_download_new" BOOLEAN,
    "language" TEXT,
    "chapters_initialized" BOOLEAN NOT NULL,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE TABLE "sources" (
    "key" TEXT NOT NULL,
    "display_name" TEXT NOT NULL,
    "base_url" TEXT NOT NULL,
    "version" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL,
    "capabilities" TEXT NOT NULL,
    "plugin_api_version" BIGINT NOT NULL,
    "hide_nsfw" BOOLEAN NOT NULL,
    "installed_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    PRIMARY KEY ("key")
);
-- #[toasty::breakpoint]
CREATE TABLE "stats_events" (
    "id" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "source" TEXT,
    "series_id" TEXT,
    "chapter_id" TEXT,
    "amount" BIGINT NOT NULL,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE INDEX "index_background_jobs_by_queue" ON "background_jobs" ("queue");
-- #[toasty::breakpoint]
CREATE INDEX "index_background_jobs_by_run_after" ON "background_jobs" ("run_after");
-- #[toasty::breakpoint]
CREATE INDEX "index_background_jobs_by_status" ON "background_jobs" ("status");
-- #[toasty::breakpoint]
CREATE INDEX "index_chapters_by_published_at_and_number_and_fetched_at" ON "chapters" ("published_at", "number", "fetched_at");
-- #[toasty::breakpoint]
CREATE INDEX "index_chapters_by_remote_chapter_id" ON "chapters" ("remote_chapter_id");
-- #[toasty::breakpoint]
CREATE INDEX "index_chapters_by_series_id" ON "chapters" ("series_id");
-- #[toasty::breakpoint]
CREATE INDEX "index_chapters_by_series_id_and_number_and_published_at" ON "chapters" ("series_id", "number", "published_at");
-- #[toasty::breakpoint]
CREATE INDEX "index_chapters_by_series_id_and_remote_chapter_id" ON "chapters" ("series_id", "remote_chapter_id");
-- #[toasty::breakpoint]
CREATE INDEX "index_download_events_by_download_id" ON "download_events" ("download_id");
-- #[toasty::breakpoint]
CREATE INDEX "index_download_events_by_download_id_and_created_at" ON "download_events" ("download_id", "created_at");
-- #[toasty::breakpoint]
CREATE INDEX "index_downloads_by_chapter_id" ON "downloads" ("chapter_id");
-- #[toasty::breakpoint]
CREATE INDEX "index_downloads_by_chapter_id_and_status_and_queued_at" ON "downloads" ("chapter_id", "status", "queued_at");
-- #[toasty::breakpoint]
CREATE INDEX "index_downloads_by_queued_at" ON "downloads" ("queued_at");
-- #[toasty::breakpoint]
CREATE INDEX "index_downloads_by_series_id" ON "downloads" ("series_id");
-- #[toasty::breakpoint]
CREATE INDEX "index_downloads_by_series_id_and_status" ON "downloads" ("series_id", "status");
-- #[toasty::breakpoint]
CREATE INDEX "index_downloads_by_status" ON "downloads" ("status");
-- #[toasty::breakpoint]
CREATE INDEX "index_downloads_by_status_and_queued_at" ON "downloads" ("status", "queued_at");
-- #[toasty::breakpoint]
CREATE INDEX "index_library_series_by_remote_series_id" ON "library_series" ("remote_series_id");
-- #[toasty::breakpoint]
CREATE INDEX "index_library_series_by_source_key" ON "library_series" ("source_key");
-- #[toasty::breakpoint]
CREATE INDEX "index_library_series_by_source_key_and_remote_series_id" ON "library_series" ("source_key", "remote_series_id");
-- #[toasty::breakpoint]
CREATE INDEX "index_stats_events_by_chapter_id" ON "stats_events" ("chapter_id");
-- #[toasty::breakpoint]
CREATE INDEX "index_stats_events_by_created_at" ON "stats_events" ("created_at");
-- #[toasty::breakpoint]
CREATE INDEX "index_stats_events_by_created_at_and_kind" ON "stats_events" ("created_at", "kind");
-- #[toasty::breakpoint]
CREATE INDEX "index_stats_events_by_kind" ON "stats_events" ("kind");
-- #[toasty::breakpoint]
CREATE INDEX "index_stats_events_by_series_id" ON "stats_events" ("series_id");
-- #[toasty::breakpoint]
CREATE INDEX "index_stats_events_by_source" ON "stats_events" ("source");
-- #[toasty::breakpoint]
-- Toasty 0.7 does not generate composite uniqueness or partial indexes.
-- Both database engines enforce these domain invariants independently of locks.
CREATE UNIQUE INDEX "library_series_source_identity" ON "library_series" ("source_key", "remote_series_id");
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "chapter_source_identity" ON "chapters" ("series_id", "remote_chapter_id");
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "one_active_download_per_chapter" ON "downloads" ("chapter_id") WHERE "status" IN ('queued', 'fetching_pages', 'downloading_assets', 'transforming_assets', 'archiving', 'cancel_requested');
