load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_test")
load("//libs/bazel/rust:defs.bzl", "rust_quality_targets")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "starlark_files",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)

rust_binary(
    name = "start",
    srcs = ["start.rs"],
    crate_name = "manga_dev_start",
    crate_root = "start.rs",
    edition = "2024",
    deps = ["@backend_crates//:rusqlite"],
    tags = ["manual"],
)

rust_test(
    name = "test_start",
    srcs = ["start.rs"],
    crate_name = "manga_dev_start_test",
    crate_root = "start.rs",
    edition = "2024",
    deps = ["@backend_crates//:rusqlite"],
)

rust_quality_targets(
    targets = [
        ":start",
        ":test_start",
    ],
)
