load("@rules_rust//rust:defs.bzl", "rust_library")
load("//libs/bazel/rust:defs.bzl", "rust_quality_targets")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "telemetry",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "backend_telemetry",
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "@backend_crates//:anyhow",
        "@backend_crates//:autometrics",
        "@backend_crates//:metrics",
        "@backend_crates//:metrics-exporter-otel",
        "@backend_crates//:opentelemetry",
        "@backend_crates//:opentelemetry-appender-tracing",
        "@backend_crates//:opentelemetry-otlp",
        "@backend_crates//:opentelemetry_sdk",
        "@backend_crates//:tokio-metrics",
        "@backend_crates//:tracing",
        "@backend_crates//:tracing-opentelemetry",
        "@backend_crates//:tracing-subscriber",
    ],
)

rust_quality_targets(
    targets = [":telemetry"],
)

filegroup(
    name = "rust_files",
    srcs = glob(
        [
            "src/**/*.rs",
            "tests/**/*.rs",
        ],
        allow_empty = True,
    ),
    tags = ["rust"],
)

filegroup(
    name = "starlark_files",
    srcs = ["BUILD.bazel"],
    tags = ["starlark"],
)
