package(default_visibility = ["//visibility:public"])

filegroup(
    name = "apps",
    srcs = [
        "//apps/svelte/kanidm-manager:build",
        "//apps/svelte/web:build",
    ],
)

test_suite(
    name = "tests",
    tests = [
        "//apps/svelte/kanidm-manager:typecheck",
        "//apps/svelte/web:test",
        "//apps/svelte/web:typecheck",
    ],
)

test_suite(
    name = "lint",
    tests = [
        "//apps/svelte/kanidm-manager:lint",
        "//apps/svelte/web:lint",
    ],
)

test_suite(
    name = "format_oxc_js_ts_check",
    tests = [
        "//apps/svelte/kanidm-manager:format_oxc_js_ts_check",
        "//apps/svelte/web:format_oxc_js_ts_check",
    ],
)

test_suite(
    name = "format_oxc_json_check",
    tests = [
        "//apps/svelte/kanidm-manager:format_oxc_json_check",
        "//apps/svelte/web:format_oxc_json_check",
    ],
)

filegroup(
    name = "starlark_files",
    srcs = [
        "BUILD.bazel",
        "//apps/svelte/kanidm-manager:starlark_files",
        "//apps/svelte/web:starlark_files",
    ],
    tags = ["starlark"],
)
