package(default_visibility = ["//visibility:public"])

filegroup(
    name = "libs",
    srcs = [
        "//libs/bazel:libs",
        "//libs/rust:libs",
        "//libs/svelte:libs",
    ],
)

test_suite(
    name = "tests",
    tests = [
        "//libs/rust:tests",
        "//libs/svelte:tests",
    ],
)

test_suite(
    name = "rustfmt_test",
    tests = [
        "//libs/bazel:rustfmt_test",
        "//libs/rust:rustfmt_test",
    ],
)

filegroup(
    name = "clippy_check",
    testonly = True,
    srcs = [
        "//libs/bazel:clippy_check",
        "//libs/rust:clippy_check",
    ],
)

filegroup(
    name = "starlark_files",
    srcs = [
        "BUILD.bazel",
        "//libs/bazel:starlark_files",
        "//libs/rust:starlark_files",
        "//libs/svelte:starlark_files",
    ],
    tags = ["starlark"],
)
