package(default_visibility = ["//visibility:public"])

filegroup(
    name = "libs",
    srcs = [
        "//libs/bazel/bazelrc:rust_files",
        "//libs/bazel/bazelrc:starlark_files",
        "//libs/bazel/buildbarn:bb_clientd_config",
        "//libs/bazel/cargo:rust_files",
        "//libs/bazel/cargo:starlark_files",
        "//libs/bazel/flamegraph:rust_files",
        "//libs/bazel/flamegraph:starlark_files",
        "//libs/bazel/quality:starlark_files",
        "//libs/bazel/rust:starlark_files",
        "//libs/bazel/upx:starlark_files",
    ],
)

test_suite(
    name = "rustfmt_test",
    tests = [
        "//libs/bazel/flamegraph:rustfmt_test",
    ],
)

filegroup(
    name = "clippy_check",
    testonly = True,
    srcs = [
        "//libs/bazel/flamegraph:clippy_check",
    ],
)

filegroup(
    name = "starlark_files",
    srcs = [
        "BUILD.bazel",
        "//libs/bazel/bazelrc:starlark_files",
        "//libs/bazel/buildbarn:starlark_files",
        "//libs/bazel/cargo:starlark_files",
        "//libs/bazel/flamegraph:starlark_files",
        "//libs/bazel/quality:starlark_files",
        "//libs/bazel/rust:starlark_files",
        "//libs/bazel/upx:starlark_files",
    ],
    tags = ["starlark"],
)
