package(default_visibility = ["//visibility:public"])

filegroup(
    name = "apps",
    srcs = [
        "//apps/clients:apps",
        "//apps/rust:apps",
        "//apps/svelte:apps",
    ],
)

test_suite(
    name = "tests",
    tests = [
        "//apps/rust:tests",
        "//apps/svelte:tests",
    ],
)

test_suite(
    name = "rustfmt_test",
    tests = [
        "//apps/rust:rustfmt_test",
    ],
)

filegroup(
    name = "clippy_check",
    testonly = True,
    srcs = [
        "//apps/rust:clippy_check",
    ],
)

filegroup(
    name = "starlark_files",
    srcs = [
        "BUILD.bazel",
        "//apps/clients:starlark_files",
        "//apps/rust:starlark_files",
        "//apps/svelte:starlark_files",
    ],
    tags = ["starlark"],
)
