use std::{fs, path::Path, process::Command};

use anyhow::{Context, Result, bail};
use codesync::{
    AuthoringMode, PlanOptions, SyncOptions, Transformation, WorkflowMode, load_config_from_str,
    plan_workflows, sync_workflows,
};
use tempfile::TempDir;

#[test]
fn starlark_config_declares_workflow() -> Result<()> {
    let config = load_config_from_str(
        "test.star",
        r#"
workflow(
    name = "demo",
    origin = git_origin(url = "internal", ref = "main"),
    destination = git_destination(url = "public", ref = "main"),
    destination_files = glob(["third_party/demo/**"], exclude = ["third_party/demo/README.md"]),
    transformations = [
        replace(before = "internal", after = "public", paths = glob(["**/*.rs"])),
        move("", "third_party/demo"),
    ],
)
"#,
    )?;

    assert_eq!(config.workflows.len(), 1);
    let workflow = &config.workflows[0];
    assert_eq!(workflow.name, "demo");
    assert_eq!(workflow.origin.reference, "main");
    assert_eq!(workflow.destination.reference, "main");
    assert_eq!(workflow.transformations.len(), 2);
    assert!(matches!(
        workflow.transformations[0],
        Transformation::Replace { .. }
    ));

    Ok(())
}

#[test]
fn copybara_style_config_declares_workflow() -> Result<()> {
    let config = load_config_from_str(
        "copy.bara.sky",
        r#"
service.migration(None)
service.notifications({})

core.workflow(
    name = "demo",
    origin = git.origin(url = "internal", fetch = "main"),
    destination = git.github_destination(
        url = "public",
        fetch = "main",
        push = "codesync/demo",
        pr_branch = "codesync/demo",
        title = "Sync demo",
        body = "Generated by codesync.",
    ),
    origin_files = glob(["src/**"]),
    destination_files = glob(["third_party/demo/**"]),
    authoring = authoring.pass_thru(),
    mode = "ITERATIVE",
    transformations = [
        core.replace(before = "internal", after = "public", paths = glob(["**/*.rs"])),
        core.move("", "third_party/demo"),
    ],
)
"#,
    )?;

    assert_eq!(config.workflows.len(), 1);
    let workflow = &config.workflows[0];
    assert_eq!(workflow.origin.reference, "main");
    assert_eq!(workflow.destination.reference, "main");
    assert_eq!(
        workflow.destination.push_reference.as_deref(),
        Some("codesync/demo")
    );
    assert_eq!(
        workflow
            .destination
            .pull_request
            .as_ref()
            .and_then(|pr| pr.branch.as_deref()),
        Some("codesync/demo")
    );
    assert_eq!(
        workflow.origin_files.as_ref().map(|files| &files.include),
        Some(&vec!["src/**".to_owned()])
    );

    Ok(())
}

#[test]
fn copybara_pr_config_declares_extended_features() -> Result<()> {
    let config = load_config_from_str(
        "copy.bara.sky",
        r#"
core.workflow(
    name = "testing",
    origin = git.github_origin(
        url = "https://github.com/CyclopsBot/testing.git",
        fetch = "main",
    ),
    destination = git.github_pr_destination(
        url = "https://github.com/CyclopsBot/testing.git",
        destination_ref = "main",
        pr_branch = "codesync/testing",
        title = "Sync testing",
        body = "Generated by codesync.",
        assignees = ["CyclopsBot"],
        labels = ["automated-sync"],
        draft = True,
        update_description = True,
    ),
    origin_files = glob(["pkg/**", ".copybara/public/**"]),
    destination_files = glob(["third_party/testing/**"]),
    authoring = authoring.overwrite(default = "TrashCan69420 <trashcan69666@gmail.com>"),
    mode = "SQUASH",
    transformations = [
        core.copy(".copybara/public", "", paths = glob(["README.md"])),
        core.remove(paths = glob(["pkg/private.txt"])),
        core.rename(before = "pkg/old_name.txt", after = "pkg/new_name.txt"),
        core.move("", "third_party/testing"),
        metadata.squash_notes(
            prefix = "Public export:\n",
            oldest_first = True,
            show_author = False,
        ),
        metadata.public_commit_messages(),
    ],
)
"#,
    )?;

    assert_eq!(config.workflows.len(), 1);
    let workflow = &config.workflows[0];
    assert_eq!(workflow.mode, WorkflowMode::Squash);
    assert_eq!(
        workflow
            .destination
            .pull_request
            .as_ref()
            .and_then(|pr| pr.branch.as_deref()),
        Some("codesync/testing")
    );
    let pr = workflow
        .destination
        .pull_request
        .as_ref()
        .context("missing pull request options")?;
    assert_eq!(pr.assignees, vec!["CyclopsBot"]);
    assert_eq!(pr.labels, vec!["automated-sync"]);
    assert!(pr.draft);
    assert!(pr.update_description);
    assert_eq!(
        workflow.authoring.as_ref().map(|authoring| &authoring.mode),
        Some(&AuthoringMode::Overwrite)
    );
    assert!(matches!(
        workflow.transformations[0],
        Transformation::Copy { .. }
    ));
    assert!(matches!(
        workflow.transformations[1],
        Transformation::Remove { .. }
    ));
    assert!(matches!(
        workflow.transformations[2],
        Transformation::Rename { .. }
    ));
    assert!(matches!(
        workflow.transformations[4],
        Transformation::MetadataSquashNotes { .. }
    ));
    assert!(matches!(
        workflow.transformations[5],
        Transformation::PublicCommitMessages { .. }
    ));

    Ok(())
}

#[test]
fn starlark_types_can_describe_codesync_helpers() -> Result<()> {
    let config = load_config_from_str(
        "typed.copy.bara.sky",
        r#"
Mode = enum("ITERATIVE", "SQUASH")
PathSpec = record(include=list[str], exclude=list[str])

def source_repo() -> GitRepository:
    return git.github_origin(url = "internal", fetch = "main")

def destination_repo() -> GitRepository:
    return git.github_pr_destination(
        url = "public",
        destination_ref = "main",
        pr_branch = "codesync/typed",
        title = "Typed sync",
    )

def files(spec: PathSpec) -> FileSet:
    return glob(spec.include, exclude = spec.exclude)

def sync_mode() -> str:
    return Mode("SQUASH").value

def public_author() -> Authoring:
    return authoring.overwrite(default = "TrashCan69420 <trashcan69666@gmail.com>")

def transforms() -> list[Transformation]:
    return [
        core.replace(before = "internal", after = "public", paths = glob(["**/*.rs"])),
        core.move("", "third_party/typed"),
    ]

core.workflow(
    name = "typed",
    origin = source_repo(),
    destination = destination_repo(),
    origin_files = files(PathSpec(include = ["src/**"], exclude = [])),
    destination_files = files(PathSpec(include = ["third_party/typed/**"], exclude = [])),
    authoring = public_author(),
    mode = sync_mode(),
    transformations = transforms(),
)
"#,
    )?;

    assert_eq!(config.workflows.len(), 1);
    let workflow = &config.workflows[0];
    assert_eq!(workflow.mode, WorkflowMode::Squash);
    assert_eq!(
        workflow.origin_files.as_ref().map(|files| &files.include),
        Some(&vec!["src/**".to_owned()])
    );
    assert_eq!(
        workflow.destination_files.include,
        vec!["third_party/typed/**".to_owned()]
    );
    assert_eq!(
        workflow
            .destination
            .pull_request
            .as_ref()
            .and_then(|pr| pr.branch.as_deref()),
        Some("codesync/typed")
    );
    assert_eq!(
        workflow.authoring.as_ref().map(|authoring| &authoring.mode),
        Some(&AuthoringMode::Overwrite)
    );
    assert_eq!(workflow.transformations.len(), 2);

    Ok(())
}

#[test]
fn starlark_types_reject_wrong_helper_values() {
    let error = load_config_from_str(
        "bad.copy.bara.sky",
        r#"
core.workflow(
    name = "bad",
    origin = "internal",
    destination = git.destination(url = "public", fetch = "main"),
    destination_files = glob(["third_party/bad/**"]),
)
"#,
    )
    .expect_err("string origin should not satisfy GitRepository");
    let error = format!("{error:#}");
    assert!(error.contains("origin"), "{error}");
    assert!(error.contains("GitRepository"), "{error}");
}

#[test]
fn transformation_lists_reject_wrong_element_types() {
    let error = load_config_from_str(
        "bad-transform.copy.bara.sky",
        r#"
core.workflow(
    name = "bad-transform",
    origin = git.origin(url = "internal", fetch = "main"),
    destination = git.destination(url = "public", fetch = "main"),
    destination_files = glob(["third_party/bad/**"]),
    transformations = ["not a transformation"],
)
"#,
    )
    .expect_err("string transformation should not satisfy Transformation");
    let error = format!("{error:#}");
    assert!(error.contains("transformations"), "{error}");
    assert!(error.contains("Transformation"), "{error}");
}

#[test]
fn sync_replays_source_head_into_destination() -> Result<()> {
    if !git_available() {
        return Ok(());
    }

    let temp = TempDir::new()?;
    let source = temp.path().join("source");
    let destination_bare = temp.path().join("destination.git");
    let destination_seed = temp.path().join("destination-seed");
    let destination_check = temp.path().join("destination-check");
    let config_path = temp.path().join("codesync.star");

    git(temp.path(), ["init", "--initial-branch=main", "source"])?;
    fs::create_dir_all(source.join("src"))?;
    fs::write(
        source.join("src/lib.rs"),
        "pub const NAME: &str = \"internal\";\n",
    )?;
    git(&source, ["add", "."])?;
    git(
        &source,
        [
            "-c",
            "user.name=Source Author",
            "-c",
            "user.email=source@example.com",
            "commit",
            "-m",
            "Add source library",
        ],
    )?;

    git(temp.path(), ["init", "--bare", "destination.git"])?;
    git(
        temp.path(),
        [
            "clone",
            destination_bare
                .to_str()
                .context("destination path was not utf-8")?,
            destination_seed
                .to_str()
                .context("seed path was not utf-8")?,
        ],
    )?;
    fs::write(destination_seed.join("README.md"), "public repo\n")?;
    git(&destination_seed, ["add", "."])?;
    git(
        &destination_seed,
        [
            "-c",
            "user.name=Public Author",
            "-c",
            "user.email=public@example.com",
            "commit",
            "-m",
            "Initial public repo",
        ],
    )?;
    git(
        &destination_seed,
        ["push", "origin", "HEAD:refs/heads/main"],
    )?;

    fs::write(
        &config_path,
        format!(
            r#"
workflow(
    name = "demo",
    origin = git_origin(url = "{}", ref = "main"),
    destination = git_destination(url = "{}", ref = "main"),
    destination_files = glob(["third_party/demo/**"]),
    transformations = [
        replace(before = "internal", after = "public", paths = glob(["**/*.rs"])),
        move("", "third_party/demo"),
    ],
)
"#,
            source.display(),
            destination_bare.display()
        ),
    )?;

    let config = codesync::load_config(&config_path)?;
    let plans = plan_workflows(&config, &PlanOptions::default())?;
    assert_eq!(plans.len(), 1);
    assert_eq!(plans[0].commits.len(), 1);

    let reports = sync_workflows(
        &config,
        &SyncOptions {
            push: true,
            ..SyncOptions::default()
        },
    )?;
    assert_eq!(reports[0].committed, 1);

    git(
        temp.path(),
        [
            "clone",
            destination_bare
                .to_str()
                .context("destination path was not utf-8")?,
            destination_check
                .to_str()
                .context("check path was not utf-8")?,
        ],
    )?;
    git(&destination_check, ["checkout", "main"])?;

    let synced = fs::read_to_string(destination_check.join("third_party/demo/src/lib.rs"))?;
    assert!(synced.contains("\"public\""));

    let log = git(&destination_check, ["log", "-1", "--format=%B"])?;
    assert!(log.contains("CodeSync-Workflow: demo"));
    assert!(log.contains("CodeSync-Source-Rev:"));

    Ok(())
}

#[test]
fn sync_squash_pr_branch_applies_copybara_transforms() -> Result<()> {
    if !git_available() {
        return Ok(());
    }

    let temp = TempDir::new()?;
    let source = temp.path().join("source");
    let destination_bare = temp.path().join("destination.git");
    let destination_seed = temp.path().join("destination-seed");
    let destination_check = temp.path().join("destination-check");
    let config_path = temp.path().join("copy.bara.sky");

    git(temp.path(), ["init", "--initial-branch=main", "source"])?;
    fs::create_dir_all(source.join("pkg"))?;
    fs::create_dir_all(source.join(".copybara/public"))?;
    fs::write(
        source.join("pkg/lib.rs"),
        "pub const NAME: &str = \"internal\";\n",
    )?;
    fs::write(source.join("pkg/private.txt"), "do not export\n")?;
    fs::write(source.join("pkg/old_name.txt"), "renamed content\n")?;
    fs::write(
        source.join(".copybara/public/README.md"),
        "public testing\n",
    )?;
    fs::write(source.join("secret.txt"), "secret\n")?;
    git(&source, ["add", "."])?;
    git(
        &source,
        [
            "-c",
            "user.name=Source Author",
            "-c",
            "user.email=source@example.com",
            "commit",
            "-m",
            "Internal implementation detail",
            "-m",
            "<BEGIN_PUBLIC>\nPublish testing package.\n<END_PUBLIC>\nDo not publish this line.",
        ],
    )?;
    let first_commit = git(&source, ["rev-parse", "HEAD"])?.trim().to_owned();
    fs::write(
        source.join("pkg/lib.rs"),
        "pub const NAME: &str = \"internal-v2\";\n",
    )?;
    git(&source, ["add", "."])?;
    git(
        &source,
        [
            "-c",
            "user.name=Second Author",
            "-c",
            "user.email=second@example.com",
            "commit",
            "-m",
            "Internal follow-up",
        ],
    )?;

    git(temp.path(), ["init", "--bare", "destination.git"])?;
    git(
        temp.path(),
        [
            "clone",
            destination_bare
                .to_str()
                .context("destination path was not utf-8")?,
            destination_seed
                .to_str()
                .context("seed path was not utf-8")?,
        ],
    )?;
    fs::write(destination_seed.join("README.md"), "public repo\n")?;
    git(&destination_seed, ["add", "."])?;
    git(
        &destination_seed,
        [
            "-c",
            "user.name=Public Author",
            "-c",
            "user.email=public@example.com",
            "commit",
            "-m",
            "Initial public repo",
        ],
    )?;
    git(
        &destination_seed,
        ["push", "origin", "HEAD:refs/heads/main"],
    )?;

    fs::write(
        &config_path,
        format!(
            r#"
core.workflow(
    name = "testing",
    origin = git.github_origin(url = "{}", fetch = "main"),
    destination = git.github_pr_destination(
        url = "{}",
        destination_ref = "main",
        pr_branch = "codesync/testing",
        title = "Sync testing",
        assignees = ["CyclopsBot"],
        labels = ["automated-sync"],
        draft = True,
    ),
    first_commit = "{}",
    origin_files = glob(["pkg/**", ".copybara/public/**"]),
    destination_files = glob(["third_party/testing/**"]),
    authoring = authoring.overwrite(default = "TrashCan69420 <trashcan69666@gmail.com>"),
    mode = "SQUASH",
    transformations = [
        core.copy(".copybara/public", "", paths = glob(["README.md"])),
        core.remove(paths = glob(["pkg/private.txt"])),
        core.rename(before = "pkg/old_name.txt", after = "pkg/new_name.txt"),
        core.replace(before = "internal", after = "public", paths = glob(["**/*.rs"])),
        core.move("", "third_party/testing"),
        metadata.squash_notes(
            prefix = "Public export:\n",
            oldest_first = True,
            show_author = False,
        ),
        metadata.public_commit_messages(),
    ],
)
"#,
            source.display(),
            destination_bare.display(),
            first_commit
        ),
    )?;

    let config = codesync::load_config(&config_path)?;
    let plans = plan_workflows(&config, &PlanOptions::default())?;
    assert_eq!(plans.len(), 1);
    assert_eq!(plans[0].mode, WorkflowMode::Squash);
    assert_eq!(plans[0].commits.len(), 2);
    assert_eq!(
        plans[0]
            .pull_request
            .as_ref()
            .and_then(|pr| pr.branch.as_deref()),
        Some("codesync/testing")
    );

    let reports = sync_workflows(
        &config,
        &SyncOptions {
            push: true,
            ..SyncOptions::default()
        },
    )?;
    assert_eq!(reports[0].pending, 2);
    assert_eq!(reports[0].committed, 1);
    assert_eq!(reports[0].empty_commits, 0);

    git(
        temp.path(),
        [
            "clone",
            destination_bare
                .to_str()
                .context("destination path was not utf-8")?,
            destination_check
                .to_str()
                .context("check path was not utf-8")?,
        ],
    )?;
    git(
        &destination_check,
        ["checkout", "-b", "check", "origin/codesync/testing"],
    )?;

    let synced = fs::read_to_string(destination_check.join("third_party/testing/pkg/lib.rs"))?;
    assert!(synced.contains("\"public-v2\""));
    assert!(
        destination_check
            .join("third_party/testing/pkg/new_name.txt")
            .exists()
    );
    assert!(
        !destination_check
            .join("third_party/testing/pkg/old_name.txt")
            .exists()
    );
    assert!(
        !destination_check
            .join("third_party/testing/pkg/private.txt")
            .exists()
    );
    assert!(
        !destination_check
            .join("third_party/testing/secret.txt")
            .exists()
    );
    assert_eq!(
        fs::read_to_string(destination_check.join("third_party/testing/README.md"))?,
        "public testing\n"
    );

    let log = git(&destination_check, ["log", "-1", "--format=%B"])?;
    assert!(log.contains("Public export:"));
    assert!(log.contains("Publish testing package."));
    assert!(log.contains("Internal Change."));
    assert!(!log.contains("Do not publish this line."));
    assert!(!log.contains("Internal follow-up"));
    assert!(log.contains("CodeSync-Workflow: testing"));
    assert!(log.contains("CodeSync-Source-Rev:"));
    assert!(log.contains("GitOrigin-RevId:"));

    let author = git(&destination_check, ["log", "-1", "--format=%an <%ae>"])?;
    assert_eq!(author.trim(), "TrashCan69420 <trashcan69666@gmail.com>");

    Ok(())
}

fn git_available() -> bool {
    Command::new("git").arg("--version").output().is_ok()
}

fn git<I, S>(cwd: &Path, args: I) -> Result<String>
where
    I: IntoIterator<Item = S>,
    S: AsRef<std::ffi::OsStr>,
{
    let output = Command::new("git")
        .current_dir(cwd)
        .args(args)
        .output()
        .with_context(|| format!("failed to run git in {}", cwd.display()))?;
    if output.status.success() {
        return String::from_utf8(output.stdout).context("git stdout was not utf-8");
    }

    bail!(
        "git failed with status {}\nstdout:\n{}\nstderr:\n{}",
        output.status,
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}
