package(default_visibility = ["//visibility:public"])

filegroup(
    name = "apps",
    srcs = [
        "//apps/rust/codesync",
        "//apps/rust/dev-start:start",
        "//apps/rust/http_proxy",
        "//apps/rust/server",
    ],
)

test_suite(
    name = "tests",
    tests = [
        "//apps/rust/codesync:test_codesync",
        "//apps/rust/http_proxy:test_http_proxy",
        "//apps/rust/server:test_server",
    ],
)

test_suite(
    name = "rustfmt_test",
    tests = [
        "//apps/rust/codesync:rustfmt_test",
        "//apps/rust/dev-start:rustfmt_test",
        "//apps/rust/http_proxy:rustfmt_test",
        "//apps/rust/server:rustfmt_test",
    ],
)

filegroup(
    name = "clippy_check",
    testonly = True,
    srcs = [
        "//apps/rust/codesync:clippy_check",
        "//apps/rust/dev-start:clippy_check",
        "//apps/rust/http_proxy:clippy_check",
        "//apps/rust/server:clippy_check",
    ],
)

filegroup(
    name = "starlark_files",
    srcs = [
        "BUILD.bazel",
        "//apps/rust/codesync:starlark_files",
        "//apps/rust/dev-start:starlark_files",
        "//apps/rust/http_proxy:starlark_files",
        "//apps/rust/server:starlark_files",
    ],
    tags = ["starlark"],
)
